socks-port: 17890
bind-address: 127.0.0.1
allow-lan: false
mode: rule
log-level: debug
ipv6: false
mmdb: null
dns:
  enable: false

proxies:
- name: reality-min
  type: vless
  server: 127.0.0.1
  port: 39444
  uuid: 3ac9b383-75a1-431c-8184-106c80eb2273
  network: tcp
  tls: true
  servername: www.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: lpaMu0U01fKbRO9mgkSiOArWZz4V0TRW7pR543Pm9Xg
    short-id: 4ac97aaf8b9b0356
  skip-cert-verify: true

rules:
- MATCH, reality-min
